#Spring Properties
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  application:
    name: ${server.appName}

  datasource:
    url: jdbc:postgresql://${server.db.host:${server.ip}}:${server.db.port}/${server.db.name}?currentSchema=${server.db.schema}
    username: ${server.db.user}
    password: ${server.db.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  properties:
    hibernate:
      default_schema: ${server.db.schema}
  flyway:
    url: jdbc:postgresql://${server.db.host:${server.ip}}:${server.db.port}/${server.db.name}
    user: ${server.db.user}
    password: ${server.db.password}
    default-schema: ${server.db.schema}
  instance:
    status-page-url-path: api/${server.name}/actuator/info
    health-check-url-path: api/${server.name}/actuator/health
  main:
    allow-bean-definition-overriding: true
server:
  shutdown: graceful
  version: ${projectVersion}
  servlet:
    session:
      timeout: 30s
#Eureka
eureka:
  client:
    should-enforce-registration-at-init: ${server.eureka.enabled}
    register-with-eureka: ${server.eureka.enabled}
    fetch-registry: ${server.eureka.enabled}
    enabled: ${server.eureka.enabled}
    should-unregister-on-shutdown: true
    registry-fetch-interval-seconds: 30
    eureka-service-url-poll-interval-seconds: 60
    service-url:
      defaultZone: http://${server.ip}:8761/eureka/
  instance:
    statusPageUrlPath: ${server.name}/info
    healthCheckUrlPath: ${server.name}/health
    instance-id: "${spring.application.name}:${spring.profiles.active}:${random.uuid}"
    #http://localhost:8090/api/wms_auth/info/health
    hostname: ${server.eureka.hostname:${spring.cloud.client.hostname}}
    prefer-ip-address: ${server.eureka.prefer-ip:true}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

#Logging
logging:
  level:
    root: ${server.logging.level}
  file:
    name: ${server.logging.filePath}

#Open-api
springdoc:
  api-docs:
    path: /security-docs

#Prometheus
management:
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus, loggers
      base-path: /${server.endpoint.main}/info
  metrics:
    enable:
      jvm: true



