server:
  appName: keeper-panda
  name: keeper_panda
  port: 8091
  ip: localhost
  eureka:
    enabled: true
  endpoint:
    main: api/v1/panda
  db:
    port: 5432
    name: postgres
    schema: keeper_panda
    user: postgres
    password: postgrespw
  logging:
    level: info
    filePath: ../logs/panda/panda.log
  pg:
    pattern: Aaaaaaaaaa00000
