server:
  appName: keeper-panda
  name: keeper_panda
  port: 0
  ip: 192.168.192.194
  endpoint:
    main: api/v1/panda
  eureka:
    enabled: true
  db:
    port: 11984
    name: keeper-postgres-db
    schema: keeper_panda
    user: ditar
    password: keeperAdmin1984
  logging:
    level: info
    filePath: ../logs/panda/panda.log
  pg:
    pattern: Aaaaaaaaaa00000
