server:
  appName: keeper-panda-service
  name: panda
  port: 0
  ip: 0.0.0.0
  eureka:
    enabled: true
  endpoint:
    main: api/panda
  db:
    port: 11984
    name: keeper-postgres-db
    schema: auth
    user: ditar
    password: keeperAdmin1984
  logging:
    level: info
    filePath: ../logs/panda/panda.log
  pg:
    pattern: Aaaaaaaaaa00000