name: panda-action-process
env:
  APPLICATION_NAME : "Keeper-Panda"
on: 
  push:
    branches: 
      - main

jobs:
  Keeper-panda:
    runs-on: self-hosted
    
    steps:
      - name: PrintAppData
        run : |
          echo "Application name2: ${{ env.APPLICATION_NAME}}"
